# mkdocs.yml
site_name: Purcell lab
site_url: https://zzz.nyspi.org/
theme:  
  name: material
  language: en
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - content.code.copy
    - search.highlight
    - search.share
  palette:
    - scheme: default
      primary: white
      accent: blue
  font: false   # use system fonts via CSS for a quieter, print-like feel
#  logo: assets/logo.svg   # optional (can omit)
  favicon: assets/favicon.png

extra_css:
  - stylesheets/extra.css

plugins:
  - search

nav:
  - Home: overview.md

  - Research areas:
      - Sleep: sleep.md
      - Genetics: genetics.md

  - People:
      - Biography: bio.md
      - Lab members: people.md

  - Resources:
      - Luna: https://zzz.nyspi.org/luna/
      - PLINK: https://zzz.nyspi.org/plink/
      - NSRR: nsrr.md

  - Selected works:
      - Publications: pubs.md
      - Tools: code.md
      
  - Contact: index.html

